export const GENERAL_QUESTIONS = [
	'O que você aprendeu ontem/esta semana?',
	'O que te anima ou te interessa em programação?',
	'Qual foi um desafio técnico recente que você enfrentou e como resolveu?',
	'Ao construir ou manter um site, quais técnicas você usa para melhorar o desempenho?',
	'Pode descrever algumas práticas recomendadas de SEO ou técnicas que você usou recentemente?',
	'Pode explicar algumas técnicas comuns ou problemas recentes resolvidos relacionados à segurança no front-end?',
	'Quais ações você tomou recentemente em seus projetos para aumentar a manutenibilidade do código?',
	'Fale sobre o seu ambiente de desenvolvimento preferido.',
	'Quais sistemas de controle de versão você conhece?',
	'Pode descrever seu fluxo de trabalho ao criar uma página web?',
	'Se você tivesse 5 arquivos de estilos diferentes, como os integraria no site?',
	'Pode descrever a diferença entre aprimoramento progressivo e degradação graciosa?',
	'Como você otimizaria os recursos de um site?',
	'Quantos recursos um navegador pode baixar de um domínio ao mesmo tempo?',
	'Quais são as exceções?',
	'Nomeie 3 maneiras de diminuir o tempo de carregamento da página (tempo percebido ou real).',
	'Se você entrasse em um projeto que usa tabs e você usa espaços, o que faria?',
	'Descreva como você criaria uma página simples de slideshow.',
	'Se pudesse dominar uma tecnologia este ano, qual seria?',
	'Explique a importância dos padrões e órgãos de padronização.',
	'O que é Flash of Unstyled Content (FOUC)? Como evitá-lo?',
	'Explique o que é ARIA e leitores de tela, e como tornar um site acessível.',
	'Explique alguns dos prós e contras de animações CSS versus animações em JavaScript.',
	'O que significa CORS e que problema ele resolve?',
	'Como você lidou com um desacordo com seu chefe ou colaborador?',
	'Quais recursos você usa para se atualizar sobre as últimas tendências de desenvolvimento e design front-end?',
	'Quais habilidades são necessárias para ser um bom desenvolvedor front-end?',
	'Qual papel você se vê desempenhando?',
	'Pode explicar o que acontece quando você digita uma URL no navegador?',
	'Descreva a diferença entre SSR e CSR. Fale sobre os prós e contras.',
	'Você está familiarizado com renderização estática?',
	'O que é reidratação? (Rehydration)',
];
