export const GENERAL_QUESTIONS = [
	'O que você aprendeu ontem/esta semana?',
	'O que te anima ou te interessa em programação?',
	'Qual foi um desafio técnico recente que você enfrentou e como resolveu?',
	'Ao construir ou manter um site, quais técnicas você usa para melhorar o desempenho?',
	'Pode descrever algumas práticas recomendadas de SEO ou técnicas que você usou recentemente?',
	'Pode explicar algumas técnicas comuns ou problemas recentes resolvidos relacionados à segurança no front-end?',
	'Quais ações você tomou recentemente em seus projetos para aumentar a manutenibilidade do código?',
	'Fale sobre o seu ambiente de desenvolvimento preferido.',
	'Quais sistemas de controle de versão você conhece?',
	'Pode descrever seu fluxo de trabalho ao criar uma página web?',
	'Se você tivesse 5 arquivos de estilos diferentes, como os integraria no site?',
	'Pode descrever a diferença entre aprimoramento progressivo e degradação graciosa?',
	'Como você otimizaria os recursos de um site?',
	'Quantos recursos um navegador pode baixar de um domínio ao mesmo tempo?',
	'Quais são as exceções?',
	'Nomeie 3 maneiras de diminuir o tempo de carregamento da página (tempo percebido ou real).',
	'Se você entrasse em um projeto que usa tabs e você usa espaços, o que faria?',
	'Descreva como você criaria uma página simples de slideshow.',
	'Se pudesse dominar uma tecnologia este ano, qual seria?',
	'Explique a importância dos padrões e órgãos de padronização.',
	'O que é Flash of Unstyled Content (FOUC)? Como evitá-lo?',
	'Explique o que é ARIA e leitores de tela, e como tornar um site acessível.',
	'Explique alguns dos prós e contras de animações CSS versus animações em JavaScript.',
	'O que significa CORS e que problema ele resolve?',
	'Como você lidou com um desacordo com seu chefe ou colaborador?',
	'Quais recursos você usa para se atualizar sobre as últimas tendências de desenvolvimento e design front-end?',
	'Quais habilidades são necessárias para ser um bom desenvolvedor front-end?',
	'Qual papel você se vê desempenhando?',
	'Pode explicar o que acontece quando você digita uma URL no navegador?',
	'Descreva a diferença entre SSR e CSR. Fale sobre os prós e contras.',
	'Você está familiarizado com renderização estática?',
	'O que é reidratação? (Rehydration)',
];

export const HTML_QUESTIONS = [
	'O que faz um doctype?',
	'Como você serve uma página com conteúdo em vários idiomas?',
	'De que tipo de coisas você deve estar ciente ao projetar ou desenvolver sites multilíngues?',
	'Para que servem os atributos data-?',
	'Considere o HTML5 como uma plataforma web aberta. Quais são os blocos de construção do HTML5?',
	'Descreva a diferença entre um cookie, sessionStorage e localStorage.',
	'Descreva a diferença entre <script>, <script async> e <script defer>.',
	'Por que geralmente é uma boa ideia posicionar os links de CSS entre <head></head> e os scripts JS antes de </body>? Você conhece alguma exceção?',
	'O que é renderização progressiva?',
	'Por que você usaria o atributo srcset em uma tag de imagem? Explique o processo que o navegador usa ao avaliar o conteúdo desse atributo.',
	'Você já usou diferentes linguagens de template HTML antes?',
	'Qual é a diferença entre canvas e svg?',
	'Quais são os elementos vazios no HTML?',
];

export const CSS_QUESTIONS = [
	'O que é a especificidade do seletor CSS e como ela funciona?',
	"Qual é a diferença entre 'resetar' e 'normalizar' o CSS? Qual você escolheria, e por quê?",
	'Descreva Floats e como eles funcionam.',
	'Descreva z-index e como o contexto de empilhamento é formado.',
	'Descreva o BFC (Block Formatting Context) e como ele funciona.',
	'Quais são as várias técnicas de limpeza (clearing) e qual é apropriada para cada contexto?',
	'Como você abordaria a correção de problemas de estilo específicos de navegadores?',
	'Como você serve suas páginas para navegadores com recursos limitados?',
	'Quais técnicas/processos você usa?',
	'Quais são as diferentes maneiras de esconder visualmente o conteúdo (e torná-lo disponível apenas para leitores de tela)?',
	'Você já usou um sistema de grid? Se sim, qual você prefere?',
	'Você já usou ou implementou media queries ou layouts/CSS específicos para dispositivos móveis?',
	'Você está familiarizado com o estilo de SVG?',
	'Você pode dar um exemplo de uma propriedade @media além de screen?',
	"Quais são algumas armadilhas ('gotchas') ao escrever CSS eficiente?",
	'Quais são as vantagens/desvantagens de usar pré-processadores CSS?',
	'Descreva o que você gosta e não gosta nos pré-processadores CSS que você usou.',
	'Como você implementaria um design web que usa fontes não-padrão?',
	'Explique como o navegador determina quais elementos correspondem a um seletor CSS.',
	'Descreva pseudo-elementos e discuta para que eles são usados.',
	'Explique sua compreensão do modelo de caixa (box model) e como você diria ao navegador, em CSS, para renderizar seu layout em diferentes modelos de caixa.',
	'O que faz * { box-sizing: border-box; }? Quais são suas vantagens?',
	'O que é a propriedade CSS display e você pode dar alguns exemplos de seu uso?',
	'Qual é a diferença entre inline e inline-block?',
	"Qual é a diferença entre os seletores 'nth-of-type()' e 'nth-child()'?",
	'Qual é a diferença entre um elemento posicionado como relativo, fixo, absoluto e estático?',
	'Quais frameworks CSS existentes você já usou localmente ou em produção? Como você os mudaria/melhoraria?',
	'Você já usou CSS Grid?',
	'Você pode explicar a diferença entre codificar um site responsivo e usar uma estratégia mobile-first?',
	'Você já trabalhou com gráficos retina? Se sim, quando e quais técnicas você usou?',
	'Há alguma razão para você querer usar translate() em vez de posicionamento absoluto, ou vice-versa? E por quê?',
	'Como a propriedade clearfix do CSS é útil?',
	'Você pode explicar a diferença entre px, em e rem no que diz respeito ao tamanho da fonte?',
	'Você pode dar um exemplo de uma pseudo-classe? Pode fornecer um caso de uso para uma pseudo-classe?',
	'Qual é a diferença entre um elemento de nível de bloco e um elemento inline? Pode fornecer exemplos de cada tipo de elemento?',
	'Qual é a diferença entre CSS Grid e Flexbox? Quando você usaria um em vez do outro?',
	'Qual é a diferença entre layouts fixos, fluidos e responsivos?',
];
